### ISSUE TITLE
Reliquary Charms Crashes Game

### ISSUE THREAD

**Issue by will-blk** [FTBTeam/FTB-Ultimate-Reloaded#143]
* **Modpack Version**: 1.4.0

* **Issue**:  Game crashes when hitting a mob while wearing an equivalent reliquary charms on a charm belt using baubbles slot. Not sure if it's a modpack compatibility issue or a mod bug in itself.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/66c944bd

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Reliquary

* **Known Fix**: Apperantly removing the charm and giving the first hit on any mob before putting it on again solves the problem.

**Comment by tfox83** [comment]
Should be fixed in 1.6.0+

**Comment by Chintagious** [comment]
@tfox83 - Looks like this is not fixed still in 1.6.0

Here are some refs I found: 
https://github.com/P3pp3rF1y/Reliquary/issues/355
https://github.com/Corosauce/Zombie_Players/issues/4
https://github.com/FTBTeam/FTB-Interactions/issues/580

My crash logs: https://paste.feed-the-beast.com/view/70b72df3
