### ISSUE TITLE
Dupe with breaker

### ISSUE THREAD

**Issue by Gaetann18** [FTBTeam/FTB-Ultimate-Reloaded#369]
* **Modpack Version**: 
1.9.1
* **Issue**: 
When we break a table containing an inventory with a breaker, it duplicates the inventory
1. https://youtu.be/f32CQUn97AE
1. https://youtu.be/jlteHAQ4y7A
1. https://youtu.be/BsLS6BNvfZA
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 
all the blocks that can break a table containing an inventory
* **Known Fix**:

**Comment by AlexIIL** [comment]
This sounds a lot like an old bug (https://github.com/BuildCraft/BuildCraft/issues/4529), that has been fixed in [7.99.24.5](https://mod-buildcraft.com/pages/download.html). What version of buildcraft is used in the pack?

**Comment by HaoSs07B** [comment]
> This sounds a lot like an old bug ([BuildCraft/BuildCraft#4529](https://github.com/BuildCraft/BuildCraft/issues/4529)), that has been fixed in [7.99.24.5](https://mod-buildcraft.com/pages/download.html). What version of buildcraft is used in the pack?

The modpack is running 7.99.24.2 so the bug is still with us :)

**Comment by AlexIIL** [comment]
Ah, ok. In which case there's nothing I can do to help other than suggest FTB (or individual players and server owners) update BC.

**Comment by 016Nojr** [comment]
Updated BC
