### ISSUE TITLE
Can't generate normal certus quartz in IF miner

### ISSUE THREAD

**Issue by Delzuar** [FTBTeam/FTB-Ultimate-Reloaded#88]
* **Modpack Version**: v1.1.0
* **Issue**: Normal certus quartz is not generating in the Industrial foregoing laser drill

* **Is it Repeatable?**:  Yes
* **Mod/s Affected**: Industrial foregoing
* **Known Fix**: There was a fixed last version removing charged certus quartz and its seem this broke the normal one. I don't think its was intented because its was specified charged certus quartz in the changelog

https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/56

**Comment by tfox83** [comment]
fixed, the mod actaully has the wrong meta by default for certus.  I fixed this on my end for the pack.  Will be in todays beta

**Comment by 1NESLEiN** [comment]
This is still an issue. Our IF Laser Miner has been running for several days (before this "fix" was applied, while running on an updated configuration with the same meta as provided from this fix) without seeing a hint of certus quartz. While we set up a BuilderCraft Quarry to supply us with certus quartz, we would like to see a real fix for this.
#104 has this issue as well.

**Comment by Delzuar** [comment]
For some reason it work fine in singleplayer but still not working properly on a server.
